# Generated by Django 5.2.17 on 2026-10-05 10:49

import biometrics.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0004_attendancesession_source'),
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('model', models.CharField(default='ZKTeco F7', max_length=80)),
                ('host', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=4370)),
                ('timezone', models.CharField(default='Asia/Manila', max_length=64, validators=[biometrics.validators.validate_timezone])),
                ('communication_password_encrypted', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], db_index=True, default='ACTIVE', max_length=10)),
                ('health', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('HEALTHY', 'Healthy'), ('DEGRADED', 'Needs attention'), ('OFFLINE', 'Offline')], db_index=True, default='UNKNOWN', max_length=10)),
                ('sync_interval_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_user_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_punch_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_lock_until', models.DateTimeField(blank=True, null=True)),
                ('firmware', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_devices', to='organizations.organization')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BiometricAttendanceProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COLLECTING', 'Collecting'), ('READY', 'Ready'), ('NEEDS_REVIEW', 'Needs review'), ('MATERIALIZED', 'Materialized'), ('CONFLICT', 'Source conflict')], db_index=True, default='COLLECTING', max_length=16)),
                ('first_punch_at', models.DateTimeField(blank=True, null=True)),
                ('last_punch_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_breaks', models.JSONField(blank=True, default=list)),
                ('punch_count', models.PositiveIntegerField(default=0)),
                ('issue_summary', models.TextField(blank=True)),
                ('candidate_closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biometric_projections', to='employees.employee')),
                ('materialized_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='biometric_projection_materialized', to='attendance.attendancesession')),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='biometric_projection', to='schedules.shift')),
            ],
        ),
        migrations.CreateModel(
            name='BiometricPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_record_id', models.CharField(blank=True, max_length=128)),
                ('terminal_user_id', models.CharField(max_length=64)),
                ('source_local_timestamp', models.CharField(max_length=64)),
                ('source_timezone', models.CharField(max_length=64, validators=[biometrics.validators.validate_timezone])),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('canonical_key', models.CharField(max_length=128)),
                ('payload_hash', models.CharField(max_length=64)),
                ('raw_payload', models.JSONField(default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punches', to='biometrics.attendancedevice')),
                ('projection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='punches', to='biometrics.biometricattendanceprojection')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BiometricPunchIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('UNMAPPED_ID', 'Unmapped terminal identity'), ('NO_SHIFT', 'No matching shift'), ('AMBIGUOUS_SHIFT', 'Ambiguous shift'), ('ODD_SEQUENCE', 'Incomplete punch sequence'), ('OPEN_BREAK', 'Open break'), ('LATE_EVIDENCE', 'Late evidence'), ('SOURCE_CONFLICT', 'Source conflict'), ('CLOCK_DRIFT', 'Device clock drift'), ('OFFLINE', 'Device offline')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='OPEN', max_length=10)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='biometrics.attendancedevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='biometric_issues', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biometric_issues', to='organizations.organization')),
                ('projection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='biometrics.biometricattendanceprojection')),
                ('punch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='biometrics.biometricpunch')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='biometric_issues_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_user_id', models.CharField(max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('fingerprint_enrolled', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identities', to='biometrics.attendancedevice')),
            ],
            options={
                'ordering': ['terminal_user_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='biometricpunch',
            name='device_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='punches', to='biometrics.deviceidentity'),
        ),
        migrations.CreateModel(
            name='DeviceIdentityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biometric_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('device_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='biometrics.deviceidentity')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biometric_assignments', to='employees.employee')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.AddField(
            model_name='biometricpunch',
            name='identity_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='punches', to='biometrics.deviceidentityassignment'),
        ),
        migrations.CreateModel(
            name='DeviceSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CONNECTION', 'Connection test'), ('USERS', 'User sync'), ('PUNCHES', 'Punch sync')], max_length=12)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='RUNNING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('users_seen', models.PositiveIntegerField(default=0)),
                ('punches_seen', models.PositiveIntegerField(default=0)),
                ('punches_created', models.PositiveIntegerField(default=0)),
                ('punches_duplicate', models.PositiveIntegerField(default=0)),
                ('issues_created', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_runs', to='biometrics.attendancedevice')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='biometric_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='biometricpunch',
            name='sync_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punches', to='biometrics.devicesyncrun'),
        ),
        migrations.CreateModel(
            name='OrganizationBiometricSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('default_sync_interval_seconds', models.PositiveIntegerField(default=120)),
                ('early_clock_in_minutes', models.PositiveIntegerField(default=30)),
                ('post_shift_capture_minutes', models.PositiveIntegerField(default=240)),
                ('duplicate_window_seconds', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='biometric_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Biometric settings',
            },
        ),
        migrations.AddIndex(
            model_name='attendancedevice',
            index=models.Index(fields=['organization', 'status'], name='bio_dev_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedevice',
            index=models.Index(fields=['organization', 'health'], name='bio_dev_org_health_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancedevice',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='biometric_device_org_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='attendancedevice',
            constraint=models.CheckConstraint(condition=models.Q(('port__gte', 1), ('port__lte', 65535)), name='biometric_device_valid_port'),
        ),
        migrations.AddConstraint(
            model_name='attendancedevice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'DISABLED'])), name='biometric_device_status_valid'),
        ),
        migrations.AddIndex(
            model_name='biometricattendanceprojection',
            index=models.Index(fields=['employee', 'status'], name='biometric_projection_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricpunchissue',
            index=models.Index(fields=['organization', 'status'], name='biometric_issue_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceidentity',
            constraint=models.UniqueConstraint(fields=('device', 'terminal_user_id'), name='biometric_identity_device_user_unique'),
        ),
        migrations.AddIndex(
            model_name='deviceidentityassignment',
            index=models.Index(fields=['device_identity', 'effective_from'], name='biometric_assign_hist_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceidentityassignment',
            index=models.Index(fields=['employee', 'effective_from'], name='biometric_assign_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesyncrun',
            index=models.Index(fields=['device', '-started_at'], name='biometric_sync_device_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricpunch',
            index=models.Index(fields=['device', 'occurred_at'], name='bio_punch_device_time_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricpunch',
            index=models.Index(fields=['terminal_user_id', 'occurred_at'], name='bio_punch_user_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='biometricpunch',
            constraint=models.UniqueConstraint(fields=('device', 'canonical_key'), name='biometric_punch_device_key_unique'),
        ),
    ]
