# Generated by Django 5.1 on 2026-10-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biometrics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="biometricattendanceprojection",
            name="algorithm_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="biometricattendanceprojection",
            name="candidate_closes_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biometricattendanceprojection",
            name="input_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="biometricattendanceprojection",
            name="last_effective_scan_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biometricattendanceprojection",
            name="last_reconciled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biometricattendanceprojection",
            name="provisional_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biometricattendanceprojection",
            name="live_state",
            field=models.CharField(
                choices=[
                    ("NONE", "No visible activity"),
                    ("WORKING", "Working — biometric provisional"),
                    ("AWAITING_NEXT_SCAN", "Awaiting next biometric scan"),
                    ("READY_FOR_REVIEW", "Ready for review"),
                    ("NEEDS_REVIEW", "Needs review"),
                    ("MATERIALIZED", "Attendance applied"),
                    ("CONFLICT", "Attendance conflict"),
                ],
                db_index=True,
                default="NONE",
                max_length=24,
            ),
        ),
        migrations.AddIndex(
            model_name="biometricattendanceprojection",
            index=models.Index(fields=["employee", "live_state"], name="bio_projection_live_emp_idx"),
        ),
    ]
