# Generated by Django 5.1 on 2026-10-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biometrics", "0002_biometricprojection_live_state"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="biometricattendanceprojection",
            index=models.Index(fields=["status", "candidate_closes_at"], name="bio_projection_due_idx"),
        ),
    ]
