server {
    listen 80;
    server_name _;
    return 308 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name _;
    server_tokens off;
    client_max_body_size 2m;
    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    location /static/ {
        alias /srv/static/;
        expires 1h;
        add_header X-Content-Type-Options nosniff;
    }
    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 95s;
    }
}
