# Generated by Django 5.2.17 on 2026-09-20 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ORGANIZATION_CREATED', 'Organization created'), ('ORGANIZATION_UPDATED', 'Organization settings updated'), ('EMPLOYEE_CREATED', 'Employee created'), ('EMPLOYEE_UPDATED', 'Employee updated'), ('EMPLOYEE_ACTIVATED', 'Employee activated'), ('EMPLOYEE_DEACTIVATED', 'Employee deactivated'), ('SHIFT_CREATED', 'Shift created'), ('SHIFT_UPDATED', 'Shift updated'), ('SHIFT_CANCELLED', 'Shift cancelled'), ('TIMESHEET_APPROVED', 'Timesheet approved'), ('TIMESHEET_REJECTED', 'Timesheet rejected')], max_length=32)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_org_created_idx'), models.Index(fields=['organization', 'action', '-created_at'], name='audit_org_action_idx')],
            },
        ),
    ]
