# Generated by Django 4.2.30 on 2026-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('ORGANIZATION_CREATED', 'Organization created'), ('ORGANIZATION_UPDATED', 'Organization settings updated'), ('EMPLOYEE_CREATED', 'Employee created'), ('EMPLOYEE_UPDATED', 'Employee updated'), ('EMPLOYEE_ACTIVATED', 'Employee activated'), ('EMPLOYEE_DEACTIVATED', 'Employee deactivated'), ('SHIFT_CREATED', 'Shift created'), ('SHIFT_UPDATED', 'Shift updated'), ('SHIFT_CANCELLED', 'Shift cancelled'), ('TIMESHEET_APPROVED', 'Timesheet approved'), ('TIMESHEET_REJECTED', 'Timesheet rejected'), ('PAYROLL_RULES_UPDATED', 'Payroll rules updated'), ('PAYROLL_RATE_ADDED', 'Employee pay rate added'), ('PAYROLL_RUN_CREATED', 'Payroll run created'), ('PAYROLL_RUN_RECALCULATED', 'Payroll run recalculated'), ('PAYROLL_RUN_REVIEWED', 'Payroll run submitted for review'), ('PAYROLL_RUN_FINALIZED', 'Payroll run finalized'), ('PAYROLL_RUN_VOIDED', 'Payroll run voided'), ('PAYROLL_ADJUSTMENT_ADDED', 'Payroll adjustment added'), ('PAYROLL_EXCEPTION_RESOLVED', 'Payroll exception resolved'), ('PAYROLL_EXPORT_ACCESSED', 'Payroll export accessed'), ('PAYROLL_STATEMENT_ACCESSED', 'Payroll statement accessed')], max_length=32),
        ),
    ]
