# Generated by Django 5.2.17 on 2026-10-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_statutory_bulk_audit_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('ORGANIZATION_CREATED', 'Organization created'), ('ORGANIZATION_UPDATED', 'Organization settings updated'), ('EMPLOYEE_CREATED', 'Employee created'), ('EMPLOYEE_UPDATED', 'Employee updated'), ('EMPLOYEE_ACTIVATED', 'Employee activated'), ('EMPLOYEE_DEACTIVATED', 'Employee deactivated'), ('SHIFT_CREATED', 'Shift created'), ('SHIFT_UPDATED', 'Shift updated'), ('SHIFT_CANCELLED', 'Shift cancelled'), ('TIMESHEET_APPROVED', 'Timesheet approved'), ('TIMESHEET_REJECTED', 'Timesheet rejected'), ('ATTENDANCE_CORRECTED', 'Attendance corrected'), ('PAYROLL_RULES_UPDATED', 'Payroll rules updated'), ('PAYROLL_PROFILE_UPDATED', 'Employee payroll profile updated'), ('PAYROLL_RATE_ADDED', 'Employee pay rate added'), ('PAYROLL_RUN_CREATED', 'Payroll run created'), ('PAYROLL_RUN_RECALCULATED', 'Payroll run recalculated'), ('PAYROLL_RUN_REVIEWED', 'Payroll run submitted for review'), ('PAYROLL_STATUTORY_REVIEWED', 'Payroll statutory item reviewed'), ('PAYROLL_STAT_ASSESSMENTS_GEN', 'Payroll statutory assessments generated'), ('PAYROLL_STATUTORY_BULK_REVIEWED', 'Payroll statutory assessments bulk reviewed'), ('PAYROLL_RUN_REOPENED', 'Payroll run returned to draft'), ('PAYROLL_RUN_FINALIZED', 'Payroll run finalized'), ('PAYROLL_RUN_VOIDED', 'Payroll run voided'), ('PAYROLL_ADJUSTMENT_ADDED', 'Payroll adjustment added'), ('PAYROLL_ADJUSTMENT_REMOVED', 'Payroll adjustment removed'), ('PAYROLL_EXCEPTION_RESOLVED', 'Payroll exception resolved'), ('PAYROLL_EXPORT_ACCESSED', 'Payroll export accessed'), ('PAYROLL_STATEMENT_ACCESSED', 'Payroll statement accessed'), ('BIOMETRIC_DEVICE_ADDED', 'Biometric device added'), ('BIOMETRIC_DEVICE_UPDATED', 'Biometric device updated'), ('BIOMETRIC_IDENTITY_ASSIGNED', 'Biometric identity assigned')], max_length=32),
        ),
    ]
