# Generated by Django 4.2.30 on 2026-09-21 12:31

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('run_type', models.CharField(choices=[('REGULAR', 'Regular'), ('OFF_CYCLE', 'Off-cycle')], default='REGULAR', max_length=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_date', models.DateField()),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'In review'), ('FINALIZED', 'Finalized'), ('VOID', 'Voided')], db_index=True, default='DRAFT', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs_finalized', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='organizations.organization')),
                ('parent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_runs', to='payroll.payrollrun')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs_prepared', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('employer_contribution_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_statements', to='employees.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['employee__last_name', 'employee__first_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PayrollTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('payable_minutes', models.PositiveIntegerField()),
                ('night_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('rate_snapshot', models.DecimalField(decimal_places=4, max_digits=12)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='payroll.payrollstatement')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='timesheets.timesheet')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(choices=[('PH', 'Philippines')], default='PH', max_length=2)),
                ('currency', models.CharField(choices=[('PHP', 'Philippine peso (PHP)')], default='PHP', max_length=3)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('SEMI_MONTHLY', 'Semi-monthly'), ('MONTHLY', 'Monthly')], default='SEMI_MONTHLY', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_settings', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('regular_day_minutes', models.PositiveSmallIntegerField(default=480)),
                ('overtime_multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.250'), max_digits=5)),
                ('rest_day_multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.300'), max_digits=5)),
                ('rest_day_overtime_multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.690'), max_digits=5)),
                ('night_start', models.TimeField(default=datetime.time(22, 0))),
                ('night_end', models.TimeField(default=datetime.time(6, 0))),
                ('night_differential_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5)),
                ('source_references', models.TextField(blank=True, help_text='Official source links and the review evidence for this version of the rules.')),
                ('reviewed_by', models.CharField(blank=True, max_length=160)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_rule_sets_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_rule_sets', to='organizations.organization')),
            ],
            options={
                'ordering': ['-effective_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('EMPLOYER_CONTRIBUTION', 'Employer contribution')], max_length=24)),
                ('code', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='CALCULATED', max_length=24)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines_created', to=settings.AUTH_USER_MODEL)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='payroll.payrollstatement')),
            ],
            options={
                'ordering': ['kind', 'code', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PayrollHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('REGULAR', 'Regular holiday'), ('SPECIAL', 'Special non-working day')], max_length=12)),
                ('worked_multiplier', models.DecimalField(decimal_places=3, max_digits=5)),
                ('overtime_multiplier', models.DecimalField(decimal_places=3, max_digits=5)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.CharField(blank=True, max_length=160)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_holidays_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_holidays', to='organizations.organization')),
            ],
            options={
                'ordering': ['date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=255)),
                ('work_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_exceptions', to='employees.employee')),
                ('resolution_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exception_resolutions', to='payroll.payrollline')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_exceptions_resolved', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='payroll.payrollrun')),
                ('timesheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_exceptions', to='timesheets.timesheet')),
            ],
            options={
                'ordering': ['resolved_at', 'employee__last_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PayrollCalculationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_previews_created', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_previews', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['-sequence'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('change_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_pay_rates_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_rates', to='employees.employee')),
            ],
            options={
                'ordering': ['-effective_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_location', models.CharField(blank=True, max_length=180)),
                ('payroll_region', models.CharField(blank=True, max_length=80)),
                ('payroll_timezone', models.CharField(blank=True, help_text="IANA timezone for the employee's actual work location, such as Asia/Manila. Blank uses the organization timezone.", max_length=64)),
                ('wage_order_reference', models.CharField(blank=True, max_length=255)),
                ('minimum_wage_confirmed', models.BooleanField(default=False)),
                ('night_differential_eligible', models.BooleanField(default=False)),
                ('rest_day', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('rank_and_file', models.BooleanField(default=True)),
                ('active_for_payroll', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_profile', to='employees.employee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='payrolltimeentry',
            constraint=models.UniqueConstraint(fields=('statement', 'timesheet'), name='payroll_time_statement_timesheet_unique'),
        ),
        migrations.AddIndex(
            model_name='payrollstatement',
            index=models.Index(fields=['employee', 'run'], name='payroll_statement_emp_run_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollstatement',
            constraint=models.UniqueConstraint(fields=('run', 'employee'), name='payroll_statement_run_employee_unique'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['organization', 'status', 'period_start'], name='payroll_run_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['organization', 'period_start', 'period_end'], name='payroll_run_org_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='payroll_run_org_reference_unique'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='payroll_run_org_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gte', models.F('period_start'))), name='payroll_run_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['DRAFT', 'REVIEW', 'FINALIZED', 'VOID'])), name='payroll_run_status_valid'),
        ),
        migrations.AddIndex(
            model_name='payrollruleset',
            index=models.Index(fields=['organization', 'effective_from'], name='payroll_rule_org_from_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollruleset',
            constraint=models.UniqueConstraint(fields=('organization', 'effective_from'), name='payroll_rule_org_effective_unique'),
        ),
        migrations.AddConstraint(
            model_name='payrollruleset',
            constraint=models.CheckConstraint(check=models.Q(('regular_day_minutes__gt', 0)), name='payroll_rule_day_minutes_positive'),
        ),
        migrations.AddConstraint(
            model_name='payrollruleset',
            constraint=models.CheckConstraint(check=models.Q(('overtime_multiplier__gte', 1)), name='payroll_rule_ot_multiplier_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollruleset',
            constraint=models.CheckConstraint(check=models.Q(('rest_day_multiplier__gte', 1)), name='payroll_rule_rest_multiplier_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollruleset',
            constraint=models.CheckConstraint(check=models.Q(('rest_day_overtime_multiplier__gte', 1)), name='payroll_rule_rest_ot_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollruleset',
            constraint=models.CheckConstraint(check=models.Q(('night_differential_rate__gte', 0)), name='payroll_rule_night_rate_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='payrollruleset',
            constraint=models.CheckConstraint(check=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='payroll_rule_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='payroll_line_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='payrollholiday',
            constraint=models.UniqueConstraint(fields=('organization', 'date'), name='payroll_holiday_org_date_unique'),
        ),
        migrations.AddConstraint(
            model_name='payrollholiday',
            constraint=models.CheckConstraint(check=models.Q(('worked_multiplier__gte', 1)), name='payroll_holiday_multiplier_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollholiday',
            constraint=models.CheckConstraint(check=models.Q(('overtime_multiplier__gte', 1)), name='payroll_holiday_ot_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollcalculationsnapshot',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='payroll_preview_run_sequence_unique'),
        ),
        migrations.AddIndex(
            model_name='employeepayrate',
            index=models.Index(fields=['employee', 'effective_from'], name='payroll_rate_emp_from_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeepayrate',
            constraint=models.CheckConstraint(check=models.Q(('hourly_rate__gt', 0)), name='payroll_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='employeepayrate',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_from'), name='payroll_rate_emp_effective_unique'),
        ),
        migrations.AddConstraint(
            model_name='employeepayrate',
            constraint=models.CheckConstraint(check=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='payroll_rate_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='employeepayprofile',
            index=models.Index(fields=['active_for_payroll', 'employee'], name='payroll_profile_active_idx'),
        ),
    ]
