# Generated by Django 4.2.30 on 2026-09-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='pay_frequency',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('SEMI_MONTHLY', 'Semi-monthly'), ('MONTHLY', 'Monthly')], default='SEMI_MONTHLY', max_length=16),
        ),
    ]
