# Generated by Django 4.2.30 on 2026-09-22 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_seed_default_profiles(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    PayrollRuleProfile = apps.get_model("payroll", "PayrollRuleProfile")
    PayrollRuleSet = apps.get_model("payroll", "PayrollRuleSet")

    for organization in Organization.objects.all().iterator():
        profile = PayrollRuleProfile.objects.create(
            organization_id=organization.pk,
            code="default",
            name="Organization default",
            description="Default payroll rules inherited by employees without an override.",
            is_default=True,
            active=True,
            created_by_id=organization.owner_id,
        )
        PayrollRuleSet.objects.filter(organization_id=organization.pk).update(rule_profile_id=profile.pk)


def backwards_seed_default_profiles(apps, schema_editor):
    PayrollRuleSet = apps.get_model("payroll", "PayrollRuleSet")
    PayrollRuleProfile = apps.get_model("payroll", "PayrollRuleProfile")
    PayrollRuleSet.objects.update(rule_profile_id=None)
    PayrollRuleProfile.objects.filter(code="default", name="Organization default").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0002_payrollrun_pay_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRuleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRuleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', 'name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='payrollruleprofile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_rule_profiles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollruleprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_rule_profiles', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='payrollruleassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_rule_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollruleassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_rule_assignments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='payrollruleassignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_rule_assignments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='payrollruleassignment',
            name='rule_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='payroll.payrollruleprofile'),
        ),
        migrations.AddField(
            model_name='payrollruleset',
            name='rule_profile',
            field=models.ForeignKey(blank=True, help_text='Reusable payroll rule profile. Legacy rows are migrated to the organization default profile.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rule_versions', to='payroll.payrollruleprofile'),
        ),
        migrations.RunPython(
            code=forwards_seed_default_profiles,
            reverse_code=backwards_seed_default_profiles,
        ),
        migrations.RemoveConstraint(
            model_name='payrollruleset',
            name='payroll_rule_org_effective_unique',
        ),
        migrations.AddConstraint(
            model_name='payrollruleset',
            constraint=models.UniqueConstraint(fields=('rule_profile', 'effective_from'), name='payroll_rule_profile_effective_unique'),
        ),
        migrations.AddConstraint(
            model_name='payrollruleprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='payroll_rule_profile_org_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='payrollruleprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='payroll_rule_profile_one_default'),
        ),
        migrations.AddIndex(
            model_name='payrollruleassignment',
            index=models.Index(fields=['organization', 'employee', 'effective_from'], name='payrule_assign_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollruleassignment',
            index=models.Index(fields=['rule_profile', 'effective_from'], name='payrule_assign_profile_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollruleassignment',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_from'), name='payroll_rule_assignment_emp_from_unique'),
        ),
        migrations.AddConstraint(
            model_name='payrollruleassignment',
            constraint=models.CheckConstraint(check=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='payroll_rule_assignment_dates_valid'),
        ),
    ]
