# Generated by Django 4.2.30 on 2026-09-27 13:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
        ('payroll', '0003_payrollruleassignment_payrollruleprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollComponentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('EMPLOYER_CONTRIBUTION', 'Employer contribution')], default='EARNING', max_length=24)),
                ('basis', models.CharField(choices=[('PER_PERIOD', 'Per payroll period'), ('PER_WORKED_DAY', 'Per worked day'), ('PER_PAYABLE_HOUR', 'Per payable hour')], default='PER_PERIOD', max_length=20)),
                ('deduct_undertime', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_component_definitions_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_component_definitions', to='organizations.organization')),
            ],
            options={
                'ordering': ['label', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeComponentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('basis', models.CharField(blank=True, choices=[('PER_PERIOD', 'Per payroll period'), ('PER_WORKED_DAY', 'Per worked day'), ('PER_PAYABLE_HOUR', 'Per payable hour')], max_length=20)),
                ('deduct_undertime', models.BooleanField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_component_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='payroll.payrollcomponentdefinition')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_component_assignments', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_component_assignments', to='organizations.organization')),
            ],
            options={
                'ordering': ['-effective_from', 'component__label', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily')], default='HOURLY', max_length=8)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('regular_day_minutes', models.PositiveSmallIntegerField(default=480)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.CharField(blank=True, max_length=160)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_compensation_versions_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_versions', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_compensation_versions', to='organizations.organization')),
            ],
            options={
                'ordering': ['-effective_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriodInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('work_date', models.DateField()),
                ('worked_day_units', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=7)),
                ('planned_day_units', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=7)),
                ('undertime_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('night_minutes', models.PositiveIntegerField(default=0)),
                ('holiday_units', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=7)),
                ('mode', models.CharField(choices=[('DAILY_REGISTER', 'Daily register'), ('ADJUSTMENT', 'Reviewed adjustment'), ('PAID_ABSENCE', 'Paid absence')], default='DAILY_REGISTER', max_length=20)),
                ('source_reference', models.CharField(max_length=255)),
                ('reviewed_by', models.CharField(max_length=160)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_period_inputs_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_period_inputs', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_period_inputs', to='organizations.organization')),
            ],
            options={
                'ordering': ['work_date', 'employee_id', 'pk'],
                'indexes': [models.Index(fields=['organization', 'period_start', 'period_end'], name='payroll_input_org_period_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollperiodinput',
            constraint=models.UniqueConstraint(fields=('employee', 'period_start', 'period_end', 'work_date'), name='payroll_input_emp_period_date_unique'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiodinput',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gte', models.F('period_start'))), name='payroll_input_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiodinput',
            constraint=models.CheckConstraint(check=models.Q(('work_date__gte', models.F('period_start')), ('work_date__lte', models.F('period_end'))), name='payroll_input_date_in_period'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiodinput',
            constraint=models.CheckConstraint(check=models.Q(('worked_day_units__gte', 0), ('planned_day_units__gte', 0), ('holiday_units__gte', 0)), name='payroll_input_units_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='payrollcomponentdefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='payroll_component_org_code_unique'),
        ),
        migrations.AddIndex(
            model_name='employeecomponentassignment',
            index=models.Index(fields=['employee', 'effective_from'], name='payroll_comp_assign_emp_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeecomponentassignment',
            constraint=models.UniqueConstraint(fields=('employee', 'component', 'effective_from'), name='payroll_component_emp_from_unique'),
        ),
        migrations.AddConstraint(
            model_name='employeecomponentassignment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payroll_component_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='employeecomponentassignment',
            constraint=models.CheckConstraint(check=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='payroll_component_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='employeecompensationversion',
            index=models.Index(fields=['employee', 'effective_from'], name='payroll_comp_emp_from_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeecompensationversion',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_from'), name='payroll_compensation_emp_from_unique'),
        ),
        migrations.AddConstraint(
            model_name='employeecompensationversion',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payroll_compensation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='employeecompensationversion',
            constraint=models.CheckConstraint(check=models.Q(('regular_day_minutes__gt', 0)), name='payroll_compensation_day_minutes_positive'),
        ),
        migrations.AddConstraint(
            model_name='employeecompensationversion',
            constraint=models.CheckConstraint(check=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='payroll_compensation_dates_valid'),
        ),
    ]
