# Generated by Django 4.2.30 on 2026-09-27 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('payroll', '0004_payrollcomponentdefinition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CASH_ADVANCE', 'Cash advance'), ('SSS_LOAN', 'SSS loan'), ('PAGIBIG_LOAN', 'Pag-IBIG loan'), ('COMPANY_LOAN', 'Company loan'), ('EMPLOYEE_CHARGE', 'Employee charge')], max_length=20)),
                ('reference', models.CharField(max_length=80)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('as_of_date', models.DateField()),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('SETTLED', 'Settled')], default='ACTIVE', max_length=12)),
                ('source_reference', models.CharField(max_length=255)),
                ('reviewed_by', models.CharField(max_length=160)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_obligations_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_obligations', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_obligations', to='organizations.organization')),
            ],
            options={
                'ordering': ['priority', 'employee_id', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='employeepayprofile',
            name='employment_status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('PROBATION', 'Probation'), ('PART_TIME', 'Part-time'), ('OTHER', 'Other')], default='REGULAR', max_length=16),
        ),
        migrations.AddField(
            model_name='employeepayprofile',
            name='minimum_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Reviewer-entered statutory/minimum daily base for the applicable wage region.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeepayprofile',
            name='pay_basis',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('MIXED', 'Mixed')], default='HOURLY', help_text="The employee's primary payroll basis. Mixed pay uses dated compensation and components.", max_length=8),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='scope_mode',
            field=models.CharField(choices=[('ALL_ACTIVE', 'All active payroll employees'), ('SELECTED', 'Selected employees')], default='ALL_ACTIVE', help_text='Payroll periods and employee scope belong to this run, not to the organization globally.', max_length=12),
        ),
        migrations.AlterField(
            model_name='employeecompensationversion',
            name='basis',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], default='HOURLY', max_length=8),
        ),
        migrations.CreateModel(
            name='PayrollRunEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_run_memberships', to='employees.employee')),
                ('included_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_run_employee_memberships_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_run_employee_memberships', to='organizations.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_memberships', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['employee__last_name', 'employee__first_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatutoryCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(choices=[('SSS', 'SSS'), ('PHILHEALTH', 'PhilHealth'), ('PAGIBIG', 'Pag-IBIG'), ('BIR', 'BIR withholding')], max_length=12)),
                ('status', models.CharField(choices=[('REVIEW', 'Needs review'), ('COVERED', 'Covered'), ('EXEMPT', 'Exempt')], default='REVIEW', max_length=8)),
                ('identifier', models.CharField(blank=True, help_text='Sensitive government identifier. Restrict access at the view and audit layers.', max_length=64)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('exemption_reason', models.CharField(blank=True, max_length=255)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.CharField(blank=True, max_length=160)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_statutory_coverages_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statutory_coverages', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_statutory_coverages', to='organizations.organization')),
            ],
            options={
                'ordering': ['agency', '-effective_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer / payroll account')], max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('account_reference', models.CharField(blank=True, help_text='Optional payroll-owner reference; do not store raw bank credentials here.', max_length=255)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_payment_methods_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_payment_methods', to='organizations.organization')),
            ],
            options={
                'ordering': ['-effective_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeObligationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SCHEDULED_INSTALLMENT', 'Scheduled installment'), ('SKIPPED', 'Skipped installment'), ('EXTERNAL_REPAYMENT', 'External repayment'), ('CORRECTION', 'Correction'), ('REVERSAL', 'Reversal'), ('FINAL_SETTLEMENT', 'Final settlement')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive repayment reduces balance; a signed correction can restore it.', max_digits=14)),
                ('transaction_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('POSTED', 'Posted'), ('VOID', 'Voided')], default='PROPOSED', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_obligation_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payroll.employeeobligation')),
                ('payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligation_transactions', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['transaction_date', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='payroll_runs', through='payroll.PayrollRunEmployee', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='StatutoryRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(choices=[('SSS', 'SSS'), ('PHILHEALTH', 'PhilHealth'), ('PAGIBIG', 'Pag-IBIG'), ('BIR', 'BIR withholding')], max_length=12)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('basis', models.CharField(blank=True, max_length=120)),
                ('employee_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('employer_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('minimum_base', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('maximum_base', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('bracket_table', models.JSONField(blank=True, default=dict)),
                ('rounding_method', models.CharField(blank=True, max_length=80)),
                ('source_reference', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=160)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statutory_rule_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statutory_rule_versions_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statutory_rule_versions', to='organizations.organization')),
            ],
            options={
                'ordering': ['agency', '-effective_from', '-pk'],
                'indexes': [models.Index(fields=['organization', 'agency', 'effective_from'], name='payroll_stat_rule_lookup_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='statutoryruleversion',
            constraint=models.UniqueConstraint(fields=('organization', 'agency', 'effective_from'), name='payroll_stat_rule_org_agency_from_unique'),
        ),
        migrations.AddConstraint(
            model_name='statutoryruleversion',
            constraint=models.CheckConstraint(check=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='payroll_stat_rule_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='statutoryruleversion',
            constraint=models.CheckConstraint(check=models.Q(('minimum_base__isnull', True), ('minimum_base__gte', 0), _connector='OR'), name='payroll_stat_rule_min_base_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='statutoryruleversion',
            constraint=models.CheckConstraint(check=models.Q(('maximum_base__isnull', True), ('maximum_base__gte', 0), _connector='OR'), name='payroll_stat_rule_max_base_nonneg'),
        ),
        migrations.AddIndex(
            model_name='payrollrunemployee',
            index=models.Index(fields=['organization', 'employee'], name='payroll_run_emp_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrunemployee',
            constraint=models.UniqueConstraint(fields=('run', 'employee'), name='payroll_run_employee_unique'),
        ),
        migrations.AddIndex(
            model_name='employeestatutorycoverage',
            index=models.Index(fields=['organization', 'employee', 'agency', 'effective_from'], name='payroll_stat_cov_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeestatutorycoverage',
            constraint=models.UniqueConstraint(fields=('employee', 'agency', 'effective_from'), name='payroll_stat_coverage_emp_agency_from_unique'),
        ),
        migrations.AddConstraint(
            model_name='employeestatutorycoverage',
            constraint=models.CheckConstraint(check=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='payroll_stat_coverage_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeepaymentmethod',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_from'), name='payroll_payment_method_emp_from_unique'),
        ),
        migrations.AddConstraint(
            model_name='employeepaymentmethod',
            constraint=models.CheckConstraint(check=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='payroll_payment_method_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeeobligationtransaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0), ('kind__in', ['CORRECTION', 'REVERSAL']), _connector='OR'), name='payroll_obligation_tx_amount_signed_only_correction'),
        ),
        migrations.AddConstraint(
            model_name='employeeobligation',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='payroll_obligation_org_reference_unique'),
        ),
        migrations.AddConstraint(
            model_name='employeeobligation',
            constraint=models.CheckConstraint(check=models.Q(('opening_balance__gte', 0)), name='payroll_obligation_opening_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='employeeobligation',
            constraint=models.CheckConstraint(check=models.Q(('installment_amount__isnull', True), ('installment_amount__gt', 0), _connector='OR'), name='payroll_obligation_installment_positive'),
        ),
    ]
