# Generated by Django 5.2.17 on 2026-09-20 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_minutes', models.PositiveIntegerField(default=0)),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('payable_minutes', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('undertime_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_REVIEW', 'Needs review')], db_index=True, default='PENDING', max_length=16)),
                ('review_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='timesheet', to='attendance.attendancesession')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='organizations.organization')),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='timesheet', to='schedules.shift')),
            ],
            options={
                'ordering': ['-shift__work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheet_reviews', to=settings.AUTH_USER_MODEL)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='timesheets.timesheet')),
            ],
            options={
                'ordering': ['-reviewed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['organization', 'status'], name='timesheets_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['organization', 'created_at'], name='timesheets_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['employee', 'created_at'], name='ts_emp_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED', 'NEEDS_REVIEW'])), name='timesheets_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(check=models.Q(('scheduled_minutes__gte', 0)), name='timesheets_scheduled_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(check=models.Q(('break_minutes__gte', 0)), name='timesheets_break_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(check=models.Q(('worked_minutes__gte', 0)), name='timesheets_worked_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(check=models.Q(('payable_minutes__gte', 0)), name='timesheets_payable_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(check=models.Q(('late_minutes__gte', 0)), name='timesheets_late_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(check=models.Q(('undertime_minutes__gte', 0)), name='timesheets_undertime_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='timesheetapproval',
            constraint=models.CheckConstraint(check=models.Q(('action__in', ['APPROVED', 'REJECTED'])), name='timesheets_review_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='timesheetapproval',
            constraint=models.CheckConstraint(check=models.Q(('action', 'APPROVED'), models.Q(('comment', ''), _negated=True), _connector='OR'), name='timesheets_rejection_comment_required'),
        ),
    ]
