# Generated by Django 5.2.17 on 2026-09-19 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(help_text='Local calendar date the shift starts on.')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('scheduled_break_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='organizations.organization')),
            ],
            options={
                'ordering': ['work_date', 'scheduled_start', 'id'],
                'indexes': [models.Index(fields=['organization', 'work_date'], name='schedules_org_date_idx'), models.Index(fields=['employee', 'work_date'], name='schedules_employee_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date'), name='schedules_employee_work_date_unique'), models.CheckConstraint(condition=models.Q(('scheduled_end__gt', models.F('scheduled_start'))), name='schedules_end_after_start'), models.CheckConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'CANCELLED'])), name='schedules_status_valid')],
            },
        ),
    ]
