# Generated by Django 5.2.17 on 2026-09-20 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_at', models.DateTimeField()),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WORKING', 'Working'), ('ON_BREAK', 'On break'), ('COMPLETED', 'Completed')], db_index=True, default='WORKING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='organizations.organization')),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_session', to='schedules.shift')),
            ],
            options={
                'ordering': ['-clock_in_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BreakSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breaks', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['started_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['organization', 'status'], name='attendance_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['employee', 'clock_in_at'], name='attendance_employee_in_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(check=models.Q(('clock_out_at__isnull', True), ('clock_out_at__gt', models.F('clock_in_at')), _connector='OR'), name='attendance_clockout_after_clockin'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('clock_out_at__isnull', False), ('status', 'COMPLETED')), models.Q(('clock_out_at__isnull', True), ('status__in', ['WORKING', 'ON_BREAK'])), _connector='OR'), name='attendance_status_clockout_consistent'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['WORKING', 'ON_BREAK', 'COMPLETED'])), name='attendance_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('clock_out_at__isnull', True)), fields=('employee',), name='attendance_one_open_per_employee'),
        ),
        migrations.AddIndex(
            model_name='breaksession',
            index=models.Index(fields=['attendance_session', 'started_at'], name='attendance_break_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='breaksession',
            constraint=models.CheckConstraint(check=models.Q(('ended_at__isnull', True), ('ended_at__gt', models.F('started_at')), _connector='OR'), name='attendance_break_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='breaksession',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('attendance_session',), name='attendance_one_open_break'),
        ),
    ]
