# Generated by Django 5.2.17 on 2026-09-29 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_clock_in_at', models.DateTimeField()),
                ('original_clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('corrected_clock_in_at', models.DateTimeField()),
                ('corrected_clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('original_breaks', models.JSONField(default=list)),
                ('corrected_breaks', models.JSONField(default=list)),
                ('reason', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='attendance.attendancesession')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_corrections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['attendance_session', '-created_at'], name='att_corr_session_idx')],
            },
        ),
    ]
