# Generated by Django 5.2.17 on 2026-10-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendancecorrection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancecorrection",
            name="corrected_breaks",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="attendancecorrection",
            name="original_breaks",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
