# Generated by Django 5.2.17 on 2026-10-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_allow_empty_correction_break_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='source',
            field=models.CharField(choices=[('EMPLOYEE_WEB', 'Employee web'), ('EMPLOYER_MANUAL', 'Employer manual'), ('BIOMETRIC', 'Biometric terminal'), ('MIXED', 'Mixed sources')], db_index=True, default='EMPLOYEE_WEB', help_text='The reviewed source that created this attendance session.', max_length=20),
        ),
    ]
